In [52]:
import pandas as pd
import os

In [53]:
punjab_cases = pd.read_csv("C:/Users/HP/OneDrive/Desktop/Projects/Judicial_DA/processed/punjab_data.csv")

In [54]:
punjab_cases

,Unnamed: 0,ddl_case_id,year,state_code,dist_code,court_no,cino,judge_position,female_defendant,female_petitioner,female_adv_def,female_adv_pet,type_name,purpose_name,disp_name,date_of_filing,date_of_decision,date_first_list,date_last_list,date_next_list
0,0,22-01-01-200100001652016,2010,22,1,1,PBLD010036142010,district and sessions court,0 male,0 male,-9999,-9999,644.0,509.0,22,2010-04-24,2016-08-30,2015-12-08,2016-08-30,2016-08-30
1,1,22-01-01-200100346662013,2010,22,1,1,PBLD010019402010,district and sessions court,0 male,0 male,0,0,644.0,509.0,22,2010-08-07,2013-11-25,2011-02-25,2013-11-20,2013-11-25
2,2,22-01-01-200100346712013,2010,22,1,1,PBLD010016392010,district and sessions court,1 female,0 male,0,0,644.0,509.0,24,2010-08-11,2011-06-07,2011-06-07,2011-06-07,2011-06-07
3,3,22-01-01-200100346842013,2010,22,1,1,PBLD010003902010,district and sessions court,0 male,1 female,-9999,-9999,644.0,509.0,5,2010-11-11,2014-11-25,2011-07-21,2014-11-14,2014-11-25
4,4,22-01-01-200100346852013,2010,22,1,1,PBLD010003912010,district and sessions court,1 female,1 female,-9999,-9999,644.0,509.0,22,2010-11-11,2014-11-25,2011-07-21,2014-11-14,2014-11-25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3197159,3197159,22-26-07-205500012412018,2018,22,26,7,PBFZC20035152018,criminal cases,0 male,0 male,-9999,0,4882.0,450.0,33,2018-12-13,2020-01-16,2019-01-15,2020-01-16,2020-01-16
3197160,3197160,22-26-07-205500012432018,2018,22,26,7,PBFZC20035692018,criminal cases,0 male,0 male,-9999,0,4882.0,450.0,33,2018-12-15,2019-12-17,2018-12-15,2019-12-17,2019-12-17
3197161,3197161,22-26-07-205500012442018,2018,22,26,7,PBFZC20035702018,criminal cases,0 male,0 male,-9999,0,4882.0,450.0,25,2018-12-15,2019-05-22,2018-12-15,2019-05-22,2019-05-22
3197162,3197162,22-26-07-205500012462018,2018,22,26,7,PBFZC20035752018,criminal cases,1 female,0 male,-9999,0,4882.0,450.0,25,2018-12-17,2019-12-14,2018-12-17,2019-12-14,2019-12-14
3197163,3197163,22-26-07-205500012522018,2018,22,26,7,PBFZC20036252018,criminal cases,0 male,0 male,-9999,0,4882.0,450.0,25,2018-12-21,2019-06-01,2018-12-21,2019-06-01,2019-06-01

### Converting dates dtype from STRING to DATE

In [55]:
date_columns = [
    'date_of_filing',
    'date_of_decision',
    'date_first_list',
    'date_last_list',
    'date_next_list'
]

punjab_cases[date_columns] = punjab_cases[date_columns].apply(
    pd.to_datetime,
    errors='coerce'
)

In [56]:
punjab_cases[['date_of_filing', 'date_of_decision']].isnull().sum()

date_of_filing           0
date_of_decision    474087
dtype: int64

In [57]:
punjab_cases['disp_name'][punjab_cases['date_of_decision'].isnull()].value_counts()

disp_name
27    423563
26     50512
13         2
5          2
48         2
51         2
22         1
24         1
16         1
14         1
Name: count, dtype: int64

In [58]:
punjab_cases['purpose_name'][punjab_cases['date_of_decision'].isnull()]

9           509.0
239        3734.0
720         509.0
752        3734.0
806        3734.0
            ...
3190724     779.0
3192409     779.0
3196422     450.0
3196556     450.0
3196746    1931.0
Name: purpose_name, Length: 474087, dtype: float64

In [59]:
disp_name_key = pd.read_csv("C:/Users/HP/OneDrive/Desktop/Projects/Judicial_DA/data/justice_data/csv/keys/disp_name_key.csv")
purpose_key = pd.read_csv("C:/Users/HP/OneDrive/Desktop/Projects/Judicial_DA/data/justice_data/csv/keys/purpose_name_key.csv")

In [60]:
disp_name_key[disp_name_key['disp_name'] == 27]

     year  disp_name              disp_name_s    count
26   2010         27                 ex-parte    14818
77   2011         27                 ex-parte    18573
128  2012         27                 ex-parte    23292
179  2013         27                 ex-parte    26770
230  2014         27                 ex-parte    31360
281  2015         27                 ex-parte    33456
332  2016         27  disposition var missing  3260488
384  2017         27  disposition var missing  4521012
436  2018         27  disposition var missing  6338472

In [61]:
disp_name_key[disp_name_key['disp_name'] == 26]

     year  disp_name              disp_name_s    count
25   2010         26  disposition var missing   613527
76   2011         26  disposition var missing   709349
127  2012         26  disposition var missing   899879
178  2013         26  disposition var missing  1244271
229  2014         26  disposition var missing  1607071
280  2015         26  disposition var missing  2259042
331  2016         26       disposed-otherwise   309716
383  2017         26       disposed-otherwise   288887
435  2018         26       disposed-otherwise   332869

In [62]:
punjab_cases['purpose_name'][punjab_cases['date_of_decision'].isnull()].value_counts()

purpose_name
450.0     70983
2975.0    60178
3206.0    47328
779.0     35223
2813.0    27874
          ...
6641.0        1
1944.0        1
5154.0        1
6613.0        1
4466.0        1
Name: count, Length: 451, dtype: int64

In [63]:
purpose_key[purpose_key['purpose_name'] == 450.0]

,year,purpose_name,purpose_name_s,count
450,2010,450.0,appearence/ws,4
5716,2011,450.0,appearance (11am-12am ...,9
12492,2012,450.0,appearance of appellant,3
19824,2013,450.0,appeara,1
27157,2014,450.0,appeal hearing,68
34917,2015,450.0,amount recovery,11
43801,2016,450.0,appear for counseling,28
51518,2017,450.0,app and amp plea,2
60304,2018,450.0,appearance,1274278

In [64]:
############################### TESTER #################################
len(punjab_cases)

3197164

# Removing Outliers

### 1). date_of_filing > date_of_decision

In [65]:
len(punjab_cases[punjab_cases['date_of_filing'] > punjab_cases['date_of_decision']])

16604

In [66]:
punjab_cases = punjab_cases[
    (punjab_cases['date_of_decision'].isna()) |
    (punjab_cases['date_of_filing'] <= punjab_cases['date_of_decision'])
]

In [67]:
len(punjab_cases)

3180560

### 2). Dates before 2010 and after 2018

In [68]:
punjab_cases['date_of_filing'][punjab_cases['date_of_filing'] < '2010-01-01'].count()

np.int64(0)

In [69]:
punjab_cases['date_of_filing'][punjab_cases['date_of_filing'] > '2018-12-31'].count()

np.int64(0)

### 3). Removing the column 'date_next_list'

In [70]:
del punjab_cases['date_next_list']

In [71]:
punjab_cases.head(1)

,Unnamed: 0,ddl_case_id,year,state_code,dist_code,court_no,cino,judge_position,female_defendant,female_petitioner,female_adv_def,female_adv_pet,type_name,purpose_name,disp_name,date_of_filing,date_of_decision,date_first_list,date_last_list
0,0,22-01-01-200100001652016,2010,22,1,1,PBLD010036142010,district and sessions court,0 male,0 male,-9999,-9999,644.0,509.0,22,2010-04-24,2016-08-30,2015-12-08,2016-08-30

### 4).

In [72]:
len(punjab_cases[punjab_cases['date_of_filing'] > punjab_cases['date_first_list']])

5759

In [73]:
punjab_cases = punjab_cases[
    (punjab_cases['date_of_decision'].isna()) |
    (punjab_cases['date_of_filing'] <= punjab_cases['date_of_decision'])
]

In [74]:
punjab_cases

,Unnamed: 0,ddl_case_id,year,state_code,dist_code,court_no,cino,judge_position,female_defendant,female_petitioner,female_adv_def,female_adv_pet,type_name,purpose_name,disp_name,date_of_filing,date_of_decision,date_first_list,date_last_list
0,0,22-01-01-200100001652016,2010,22,1,1,PBLD010036142010,district and sessions court,0 male,0 male,-9999,-9999,644.0,509.0,22,2010-04-24,2016-08-30,2015-12-08,2016-08-30
1,1,22-01-01-200100346662013,2010,22,1,1,PBLD010019402010,district and sessions court,0 male,0 male,0,0,644.0,509.0,22,2010-08-07,2013-11-25,2011-02-25,2013-11-20
2,2,22-01-01-200100346712013,2010,22,1,1,PBLD010016392010,district and sessions court,1 female,0 male,0,0,644.0,509.0,24,2010-08-11,2011-06-07,2011-06-07,2011-06-07
3,3,22-01-01-200100346842013,2010,22,1,1,PBLD010003902010,district and sessions court,0 male,1 female,-9999,-9999,644.0,509.0,5,2010-11-11,2014-11-25,2011-07-21,2014-11-14
4,4,22-01-01-200100346852013,2010,22,1,1,PBLD010003912010,district and sessions court,1 female,1 female,-9999,-9999,644.0,509.0,22,2010-11-11,2014-11-25,2011-07-21,2014-11-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3197159,3197159,22-26-07-205500012412018,2018,22,26,7,PBFZC20035152018,criminal cases,0 male,0 male,-9999,0,4882.0,450.0,33,2018-12-13,2020-01-16,2019-01-15,2020-01-16
3197160,3197160,22-26-07-205500012432018,2018,22,26,7,PBFZC20035692018,criminal cases,0 male,0 male,-9999,0,4882.0,450.0,33,2018-12-15,2019-12-17,2018-12-15,2019-12-17
3197161,3197161,22-26-07-205500012442018,2018,22,26,7,PBFZC20035702018,criminal cases,0 male,0 male,-9999,0,4882.0,450.0,25,2018-12-15,2019-05-22,2018-12-15,2019-05-22
3197162,3197162,22-26-07-205500012462018,2018,22,26,7,PBFZC20035752018,criminal cases,1 female,0 male,-9999,0,4882.0,450.0,25,2018-12-17,2019-12-14,2018-12-17,2019-12-14
3197163,3197163,22-26-07-205500012522018,2018,22,26,7,PBFZC20036252018,criminal cases,0 male,0 male,-9999,0,4882.0,450.0,25,2018-12-21,2019-06-01,2018-12-21,2019-06-01

# exporting punjab_cases to processed-> export-> punjab_cases

In [77]:
punjab_cases.to_csv(r"C:/Users/HP/OneDrive/Desktop/Projects/Judicial_DA/processed/export/Punjab_Data_Cleaned.csv", index=False)