In [3]:
import pandas as pd
import tqdm.auto as tqdm
import os

# act_key

In [4]:
act_key = pd.read_csv("C:/Users/HP/OneDrive/Desktop/Projects/Judicial_DA/data/justice_data/csv/keys/act_key.csv")

In [5]:
act_key

                                  act_s    count      act
0                                   NaN  11282.0      NaN
1                                     '  11160.0      1.0
2                                    ''  20887.0      2.0
3           'Tamil Nadu City Police Act    371.0      3.0
4      (BOMBAY) NATIONAL PARK ACT, 1950      2.0      4.0
...                                 ...      ...      ...
29852                        xxM.T.RAct     96.0  29852.0
29853                     xxP.N.D.T.Act   2245.0  29853.0
29854                       xxS.C.E.Act     45.0  29854.0
29855                                 y      6.0  29855.0
29856                     zila parishad    565.0  29856.0

[29857 rows x 3 columns]

In [6]:
act_key.value_counts()

act_s                                                     count    act
'                                                         11160.0  1.0        1
''                                                        20887.0  2.0        1
'Tamil Nadu City Police Act                               371.0    3.0        1
(BOMBAY) NATIONAL PARK ACT, 1950                          2.0      4.0        1
(Bihar) Narcotic Drugs and Psychotropic Substance4 Rules  2594.0   5.0        1
                                                                             ..
xxM.T.RAct                                                96.0     29852.0    1
xxP.N.D.T.Act                                             2245.0   29853.0    1
xxS.C.E.Act                                               45.0     29854.0    1
y                                                         6.0      29855.0    1
zila parishad                                             565.0    29856.0    1
Name: count, Length: 29853, dtype: int64

# cases_court_key

In [7]:
cases_court_key = pd.read_csv("C:/Users/HP/OneDrive/Desktop/Projects/Judicial_DA/data/justice_data/csv/keys/cases_court_key.csv")

In [8]:
cases_court_key

,year,state_code,state_name,district_name,dist_code,court_no,court_name
0,2010,1,Maharashtra,Nandurbar,1,1,Chief Judcial Magistrate Nandurbar
1,2010,1,Maharashtra,Nandurbar,1,2,Civil Court Senior Division Nandurbar
2,2010,1,Maharashtra,Nandurbar,1,3,"DISTRICT AND SESSIONS COURT, NANDURBAR"
3,2010,1,Maharashtra,Nandurbar,1,4,Civil Court J.D. and J.M.F.C.Taloda
4,2010,1,Maharashtra,Nandurbar,1,5,Jt. Civil Court J.D. and J.M.F.C. Shahada
...,...,...,...,...,...,...,...
59423,2018,33,Ladakh,Kargil,1,2,Principal District Judge
59424,2018,33,Ladakh,Kargil,1,3,Chief Judicial Magistrate
59425,2018,33,Ladakh,Leh,2,1,Principal Session Judge
59426,2018,33,Ladakh,Leh,2,2,Principal District Judge
59427,2018,33,Ladakh,Leh,2,3,Chief Judicial Magistrate

In [9]:
cases_court_key[cases_court_key['state_name'] == 'Punjab']

,year,state_code,state_name,district_name,dist_code,court_no,court_name
5594,2010,22,Punjab,Ludhiana,1,1,"District and Sessions Courts, Ludhiana"
5595,2010,22,Punjab,Ludhiana,1,2,Civil Courts Khanna
5596,2010,22,Punjab,Ludhiana,1,3,"Civil Courts, Ludhiana"
5597,2010,22,Punjab,Ludhiana,1,4,"Criminal Courts, Ludhiana"
5598,2010,22,Punjab,Ludhiana,1,5,Criminal Courts Khanna
...,...,...,...,...,...,...,...
58841,2018,22,Punjab,Fazilka,26,3,"Criminal Courts, Abohar"
58842,2018,22,Punjab,Fazilka,26,4,"Civil Courts, Abohar"
58843,2018,22,Punjab,Fazilka,26,5,"Civil Courts, Jalalabad"
58844,2018,22,Punjab,Fazilka,26,6,"Criminal Courts, Jalalabad"
58845,2018,22,Punjab,Fazilka,26,7,"Criminal Courts, Fazilka"

In [32]:
1379 / 23      # 23 districts

59.95652173913044

# cases_district_key

In [10]:
cases_district_key = pd.read_csv("C:/Users/HP/OneDrive/Desktop/Projects/Judicial_DA/data/justice_data/csv/keys/cases_district_key.csv")

In [11]:
cases_district_key

,year,state_code,state_name,dist_code,district_name,pc11_state_name,pc11_state_id,pc11_district_name,pc11_district_id
0,2010,2,Andhra Pradesh,7,Kadapa,andhra pradesh,28,NaN,NaN
1,2010,2,Andhra Pradesh,15,Nellore,andhra pradesh,28,NaN,NaN
2,2010,8,Bihar,10,Motihari,bihar,10,NaN,NaN
3,2010,8,Bihar,4,Saran at Chapra,bihar,10,NaN,NaN
4,2010,8,Bihar,28,Bettiah,bihar,10,NaN,NaN
...,...,...,...,...,...,...,...,...,...
627,2010,16,West Bengal,14,North Twenty Four Parganas,west bengal,19,north twenty four parganas,337.0
628,2010,16,West Bengal,7,Paschim Medinpur,west bengal,19,paschim medinipur,344.0
629,2010,16,West Bengal,9,Purba Medinipur,west bengal,19,purba medinipur,345.0
630,2010,16,West Bengal,10,Purulia,west bengal,19,puruliya,340.0
631,2010,16,West Bengal,20,South Twenty Four Parganas,west bengal,19,south twenty four parganas,343.0

In [12]:
cases_district_key[cases_district_key['state_name'] == 'Punjab']

,year,state_code,state_name,dist_code,district_name,pc11_state_name,pc11_state_id,pc11_district_name,pc11_district_id
58,2010,22,Punjab,26,Fazilka,punjab,3,NaN,NaN
59,2010,22,Punjab,6,Ferozepur,punjab,3,NaN,NaN
60,2010,22,Punjab,14,Sri Muktsar Sahib,punjab,3,NaN,NaN
61,2010,22,Punjab,15,SBS Nagar,punjab,3,NaN,NaN
62,2010,22,Punjab,21,Pathankot,punjab,3,NaN,NaN
63,2010,22,Punjab,24,Mohali,punjab,3,NaN,NaN
457,2010,22,Punjab,8,Amritsar,punjab,3,amritsar,49.0
458,2010,22,Punjab,16,Barnala,punjab,3,barnala,54.0
459,2010,22,Punjab,17,Bathinda,punjab,3,bathinda,46.0
460,2010,22,Punjab,9,Faridkot,punjab,3,faridkot,45.0
461,2010,22,Punjab,4,Fatehgarh Sahib,punjab,3,fatehgarh sahib,40.0
462,2010,22,Punjab,10,Gurdaspur,punjab,3,gurdaspur,35.0
463,2010,22,Punjab,18,Hoshiarpurr,punjab,3,hoshiarpur,38.0
464,2017,22,Punjab,18,Hoshiarpur,punjab,3,hoshiarpur,38.0
465,2010,22,Punjab,2,Jalandhar,punjab,3,jalandhar,37.0
466,2010,22,Punjab,11,Kapurthala,punjab,3,kapurthala,36.0
467,2010,22,Punjab,1,Ludhiana,punjab,3,ludhiana,41.0
468,2010,22,Punjab,13,Mansa,punjab,3,mansa,47.0
469,2010,22,Punjab,12,Moga,punjab,3,moga,42.0
470,2010,22,Punjab,5,Patiala,punjab,3,patiala,48.0
471,2010,22,Punjab,3,Rupnagar,punjab,3,rupnagar,51.0
472,2010,22,Punjab,19,Sangrur,punjab,3,sangrur,53.0
473,2010,22,Punjab,23,Tarn Taran,punjab,3,tarn taran,50.0

# cases_state_key

In [13]:
cases_state_key = pd.read_csv("C:/Users/HP/OneDrive/Desktop/Projects/Judicial_DA/data/justice_data/csv/keys/cases_state_key.csv")

In [14]:
cases_state_key

     year  state_code      state_name pc11_state_name  pc11_state_id
0    2018           2  Andhra Pradesh  andhra pradesh             28
1    2011           2  Andhra Pradesh  andhra pradesh             28
2    2011          29       Telangana  andhra pradesh             28
3    2010          29       Telangana  andhra pradesh             28
4    2014           2  Andhra Pradesh  andhra pradesh             28
..    ...         ...             ...             ...            ...
282  2010          16     West Bengal     west bengal             19
283  2017          16     West Bengal     west bengal             19
284  2013          16     West Bengal     west bengal             19
285  2014          16     West Bengal     west bengal             19
286  2015          16     West Bengal     west bengal             19

[287 rows x 5 columns]

In [15]:
cases_state_key[cases_state_key['state_name'] == 'Punjab']

     year  state_code state_name pc11_state_name  pc11_state_id
215  2013          22     Punjab          punjab              3
216  2010          22     Punjab          punjab              3
217  2018          22     Punjab          punjab              3
218  2017          22     Punjab          punjab              3
219  2011          22     Punjab          punjab              3
220  2012          22     Punjab          punjab              3
221  2016          22     Punjab          punjab              3
222  2015          22     Punjab          punjab              3
223  2014          22     Punjab          punjab              3

# disp_name_key

In [16]:
disp_name_key = pd.read_csv("C:/Users/HP/OneDrive/Desktop/Projects/Judicial_DA/data/justice_data/csv/keys/disp_name_key.csv")

In [17]:
disp_name_key

     year  disp_name  disp_name_s   count
0    2010          1     258 crpc   15765
1    2010          2       abated   22021
2    2010          3    absconded   16773
3    2010          4    acquitted  406015
4    2010          5      allowed  244023
..    ...        ...          ...     ...
457  2018         48       stayed     185
458  2018         49  transferred  394249
459  2018         50  uncontested     575
460  2018         51      untrace   29986
461  2018         52    withdrawn  221903

[462 rows x 4 columns]

In [18]:
disp_name_key['disp_name_s'].value_counts()

disp_name_s
258 crpc                   9
abated                     9
absconded                  9
acquitted                  9
allowed                    9
appeal accepted            9
award                      9
bail granted               9
bail refused               9
bail rejected              9
cancelled                  9
closed                     9
committed                  9
compounded                 9
compromise                 9
confession                 9
contest-allowed            9
converted                  9
convicted                  9
decided                    9
died                       9
dismissed                  9
disposal in lok adalat     9
disposed                   9
disposed-otherwise         9
disposition var missing    9
ex-parte                   9
execution                  9
fine                       9
judgement                  9
not press                  9
other                      9
otherwise                  9
p.o. consign               9
partly decreed             9
plea bargaining            9
plead guilty               9
prison                     9
probation                  9
procedural                 9
quash                      9
referred to lok adalat     9
reject                     9
remanded                   9
settled                    9
sine die                   9
stayed                     9
transferred                9
uncontested                9
untrace                    9
withdrawn                  9
bail order                 3
Name: count, dtype: int64

# judge_case_merge_key

In [19]:
judge_case_merge_key = pd.read_csv("C:/Users/HP/OneDrive/Desktop/Projects/Judicial_DA/data/justice_data/csv/keys/judge_case_merge_key.csv")

In [20]:
judge_case_merge_key

                       ddl_case_id  ddl_filing_judge_id  ddl_decision_judge_id
0         01-01-01-201900000022018                  5.0                    5.0
1         01-01-01-201900000032017                  5.0                    5.0
2         01-01-01-201900000032018                 94.0                   94.0
3         01-01-01-201900000042016                  3.0                    5.0
4         01-01-01-201900000042018                156.0                  156.0
...                            ...                  ...                    ...
12901141  30-02-06-203500000292016                  NaN                98408.0
12901142  30-02-06-203500000302016                  NaN                98427.0
12901143  30-02-06-203500000322016                  NaN                98462.0
12901144  30-02-06-203500000342016                  NaN                98427.0
12901145  30-02-06-203600001332016                  NaN                98408.0

[12901146 rows x 3 columns]

# purpose_name_key

In [21]:
purpose_name_key = pd.read_csv("C:/Users/HP/OneDrive/Desktop/Projects/Judicial_DA/data/justice_data/csv/keys/purpose_name_key.csv")

In [22]:
purpose_name_key

,year,purpose_name,purpose_name_s,count
0,2010,NaN,NaN,254130
1,2010,1.0,'b' f/r report,2
2,2010,2.0,'p' hearing,1
3,2010,3.0,(10am to 1pm ...,131
4,2010,4.0,(2pm to 5pm ...,58
...,...,...,...,...
68120,2018,8266.0,ws nfl hearing,1
68121,2018,8267.0,ws obj to ia,28
68122,2018,8268.0,ws of respondent,9
68123,2018,8269.0,ws/ objection,1009
68124,2018,8270.0,ws/wo,6

# section_key

In [23]:
section_key = pd.read_csv("C:/Users/HP/OneDrive/Desktop/Projects/Judicial_DA/data/justice_data/csv/keys/section_key.csv")

In [24]:
section_key

                          section_s    count    section
0                               NaN  4834909        NaN
1        !#11bofHindumarriageAt1955        1        1.0
2                            !3 (B)        1        2.0
3                        !3(1)(i-a)        1        3.0
4                             !3(3)        1        4.0
...                             ...      ...        ...
2113914                       ‌‌‌65        1  2113914.0
2113915                         ‍us        1  2113915.0
2113916                 ‍us21Rule11        1  2113916.0
2113917            •\tUo21rule37,38        1  2113917.0
2113918                           ●       31  2113918.0

[2113919 rows x 3 columns]

# type_name_key

In [25]:
type_name_key = pd.read_csv("C:/Users/HP/OneDrive/Desktop/Projects/Judicial_DA/data/justice_data/csv/keys/type_name_key.csv")

In [26]:
type_name_key

       year  type_name          type_name_s  count
0      2010        1.0             (m) t.s.     18
1      2010        2.0                 (sc)      2
2      2010        3.0           ..mact 166     97
3      2010        4.0   04 complaint cases     19
4      2010        5.0     04 criminal case     21
...     ...        ...                  ...    ...
62709  2018     7529.0      xxxxxspl t.ndps      3
62710  2018     7530.0   zila panchayat act    217
62711  2018     7531.0  zilla panchayat act     17
62712  2018     7532.0     zima 457 cr.p.c.      9
62713  2018     7533.0    zimma application     54

[62714 rows x 4 columns]

In [27]:
type_name_key.sort_values('count', ascending=False)

       year  type_name     type_name_s   count
56157  2018      977.0              cc  900758
48605  2017      981.0              cc  899445
41170  2016      929.0              cc  895703
33719  2015      956.0              cc  787564
26503  2014      915.0              cc  766294
...     ...        ...             ...     ...
43136  2016     2895.0  factories act.       1
23586  2013     5088.0  pocso act 2012       1
15429  2012     3749.0  mat. execution       1
15426  2012     3746.0       mat. apl.       1
62702  2018     7522.0         xxxxxos       1

[62714 rows x 4 columns]

# judges_clean

In [28]:
judges_clean = pd.read_csv("C:/Users/HP/OneDrive/Desktop/Projects/Judicial_DA/data/justice_data/csv/judges_clean.csv")

In [29]:
judges_clean

,ddl_judge_id,state_code,dist_code,court_no,judge_position,female_judge,start_date,end_date
0,1,1,1,1,chief judicial magistrate,0 nonfemale,20-09-2013,20-02-2014
1,2,1,1,1,chief judicial magistrate,0 nonfemale,31-10-2013,20-02-2014
2,3,1,1,1,chief judicial magistrate,0 nonfemale,21-02-2014,31-05-2016
3,4,1,1,1,chief judicial magistrate,0 nonfemale,01-06-2016,06-06-2016
4,5,1,1,1,chief judicial magistrate,0 nonfemale,06-06-2016,07-07-2018
...,...,...,...,...,...,...,...,...
98473,98474,30,2,9,criminal cases,1 female,21-04-2004,14-11-2013
98474,98475,30,2,9,criminal cases,1 female,16-01-2015,16-01-2016
98475,98476,30,2,9,criminal cases,1 female,09-12-2016,31-07-2017
98476,98477,30,2,10,criminal cases,1 female,15-05-2017,28-01-2019
98477,98478,30,2,10,criminal cases,0 nonfemale,28-01-2019,NaN

In [30]:
judges_clean['judge_position'].value_counts()

judge_position
district and sessions court                   20286
chief judicial magistrate                     14373
civil judge senior division                   13632
civil judge junior division                    9918
civil court                                    5416
                                              ...
2-metropolitan magistrate court                   1
special court for atrocities against women        1
spl majistrate courts, miryalaguda                1
magistrate court, nalgonda                        1
additional jmfc                                   1
Name: count, Length: 565, dtype: int64

In [31]:
judges_clean['female_judge'].value_counts()

female_judge
0 nonfemale      67540
1 female         27202
-9998 unclear     3735
Name: count, dtype: int64

In [33]:
judges_clean['female_judge'].value_counts()

female_judge
0 nonfemale      67540
1 female         27202
-9998 unclear     3735
Name: count, dtype: int64