In [1]:
import pandas as pd

In [2]:
df_2010 = pd.read_csv("C:/Users/HP/OneDrive/Desktop/Projects/Judicial_DA/data/justice_data/csv/cases/cases_2010.csv")

df_2011 = pd.read_csv("C:/Users/HP/OneDrive/Desktop/Projects/Judicial_DA/data/justice_data/csv/cases/cases_2011.csv")

df_2012 = pd.read_csv("C:/Users/HP/OneDrive/Desktop/Projects/Judicial_DA/data/justice_data/csv/cases/cases_2012.csv")

df_2013 = pd.read_csv("C:/Users/HP/OneDrive/Desktop/Projects/Judicial_DA/data/justice_data/csv/cases/cases_2013.csv")

df_2014 = pd.read_csv("C:/Users/HP/OneDrive/Desktop/Projects/Judicial_DA/data/justice_data/csv/cases/cases_2014.csv")

df_2015 = pd.read_csv("C:/Users/HP/OneDrive/Desktop/Projects/Judicial_DA/data/justice_data/csv/cases/cases_2015.csv")

df_2016 = pd.read_csv("C:/Users/HP/OneDrive/Desktop/Projects/Judicial_DA/data/justice_data/csv/cases/cases_2016.csv")

df_2017 = pd.read_csv("C:/Users/HP/OneDrive/Desktop/Projects/Judicial_DA/data/justice_data/csv/cases/cases_2017.csv")

df_2018 = pd.read_csv("C:/Users/HP/OneDrive/Desktop/Projects/Judicial_DA/data/justice_data/csv/cases/cases_2018.csv")

In [3]:
df_2010

,ddl_case_id,year,state_code,dist_code,court_no,cino,judge_position,female_defendant,female_petitioner,female_adv_def,female_adv_pet,type_name,purpose_name,disp_name,date_of_filing,date_of_decision,date_first_list,date_last_list,date_next_list
0,01-01-01-200308002162010,2010,1,1,1,MHNB030013812010,chief judicial magistrate,0 male,1 female,0,-9998,790,5228.0,42,2010-12-13,2011-06-19,2011-06-08,2011-06-20,2011-06-24
1,01-01-01-200707000172010,2010,1,1,1,MHNB030004552010,chief judicial magistrate,-9998 unclear,1 female,-9999,0,2587,3627.0,42,2010-02-25,2010-11-21,2010-08-06,2010-08-06,2010-11-30
2,01-01-01-200707000182010,2010,1,1,1,MHNB030004562010,chief judicial magistrate,-9998 unclear,-9998 unclear,-9999,0,2587,3627.0,42,2010-02-25,2010-11-21,2010-08-06,2010-08-06,2010-11-30
3,01-01-01-200707000192010,2010,1,1,1,MHNB030004582010,chief judicial magistrate,-9998 unclear,1 female,-9999,0,2587,3627.0,42,2010-02-25,2010-11-21,2010-08-06,2010-08-06,2010-11-30
4,01-01-01-200707000202010,2010,1,1,1,MHNB030004592010,chief judicial magistrate,-9998 unclear,-9998 unclear,-9999,0,2587,3627.0,42,2010-02-25,2010-11-21,2010-08-06,2010-08-06,2010-11-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4281322,32-01-01-211900000022010,2010,32,1,1,UTDN010005962010,principal district and sessions court,-9998 unclear,1 female,-9999,1,4684,3280.0,30,2010-06-07,2010-07-12,2010-07-12,2010-07-12,2010-07-12
4281323,32-01-01-212400000102010,2010,32,1,1,UTDN010000012010,principal district and sessions court,1 female,-9998 unclear,0,-9998,509,3348.0,42,2010-02-25,2013-12-22,2012-01-19,2013-12-12,2013-12-22
4281324,32-01-01-212500000012010,2010,32,1,1,UTDN010006212010,principal district and sessions court,-9998 unclear,1 female,-9999,0,3214,3348.0,42,2010-11-29,2013-04-21,2012-07-13,2013-03-15,2013-04-21
4281325,32-01-01-212600000012010,2010,32,1,1,UTDN010006032010,principal district and sessions court,-9998 unclear,-9998 unclear,0,0,2399,3280.0,20,2010-12-01,2019-11-30,2011-04-01,2019-11-30,2019-11-30
4281326,32-01-01-213000000802010,2010,32,1,1,UTDN010006312010,principal district and sessions court,1 female,-9998 unclear,-9999,0,4401,3734.0,22,2010-03-02,2017-01-07,2013-01-16,2017-01-07,2017-01-07

In [3]:
df_2010['judge_position'].value_counts().head(50)

judge_position
district and sessions court                         756161
chief judicial magistrate                           566262
judicial magistrate court                           425816
civil court                                         326011
civil judge senior division                         241252
civil judge junior division                         237400
criminal cases                                      215779
principal district and sessions court               127444
principal civil judge                               114708
additional chief judicial magistrate                112442
chief metropolitan magistrate                        86932
jmfc                                                 70758
metropolitan magistrate court                        70754
principal civil judge senior division                68654
taluka court                                         67656
city civil and sessions court                        64325
civil judge                                          62023
small cause court                                    58128
family court                                         55420
additional district judge                            41771
sub court                                            41411
principal civil judge junior division                29369
motor accidents claims tribunal                      25722
munsiff first class court                            22630
labour court                                         20466
additional district and sessions court               19091
motor vehicle court, nagpur.                         19057
additional metropolitan magistrate court             18069
principal district judge                             17656
principal judge family court                         15147
1-jmfc                                               14035
subdivisional judicial magistrate                    13144
district munsiff first class                         10890
additional civil judge and judicial magistrate       10586
munsiff                                               9918
additional chief metropolitan magistrate              9529
principal sub court                                   8549
polc and poit                                         7773
railway ner                                           7404
3-jmfc                                                7286
2-additional civil judge and judicial magistrate      5582
junior division                                       5423
industrial court                                      5249
mm court                                              4784
additional court                                      4673
chief judge court                                     4541
petty court                                           4214
munsiff magistrate court                              4022
senior court hyderabad                                3789
additional civil judge junior division                3575
Name: count, dtype: int64

In [4]:
len(df_2010['state_code'].value_counts())

31

In [5]:
state_key = pd.read_csv("C:/Users/HP/OneDrive/Desktop/Projects/Judicial_DA/data/justice_data/csv/keys/cases_state_key.csv")

In [6]:
state_key

     year  state_code      state_name pc11_state_name  pc11_state_id
0    2018           2  Andhra Pradesh  andhra pradesh             28
1    2011           2  Andhra Pradesh  andhra pradesh             28
2    2011          29       Telangana  andhra pradesh             28
3    2010          29       Telangana  andhra pradesh             28
4    2014           2  Andhra Pradesh  andhra pradesh             28
..    ...         ...             ...             ...            ...
282  2010          16     West Bengal     west bengal             19
283  2017          16     West Bengal     west bengal             19
284  2013          16     West Bengal     west bengal             19
285  2014          16     West Bengal     west bengal             19
286  2015          16     West Bengal     west bengal             19

[287 rows x 5 columns]

In [7]:
state_key[state_key['state_name'] == 'Punjab']

     year  state_code state_name pc11_state_name  pc11_state_id
215  2013          22     Punjab          punjab              3
216  2010          22     Punjab          punjab              3
217  2018          22     Punjab          punjab              3
218  2017          22     Punjab          punjab              3
219  2011          22     Punjab          punjab              3
220  2012          22     Punjab          punjab              3
221  2016          22     Punjab          punjab              3
222  2015          22     Punjab          punjab              3
223  2014          22     Punjab          punjab              3

In [8]:
df_2010[df_2010['state_code'] == 22]

,ddl_case_id,year,state_code,dist_code,court_no,cino,judge_position,female_defendant,female_petitioner,female_adv_def,female_adv_pet,type_name,purpose_name,disp_name,date_of_filing,date_of_decision,date_first_list,date_last_list,date_next_list
3613256,22-01-01-200100001652016,2010,22,1,1,PBLD010036142010,district and sessions court,0 male,0 male,-9999,-9999,644,509.0,22,2010-04-24,2016-08-30,2015-12-08,2016-08-30,2016-08-30
3613257,22-01-01-200100346662013,2010,22,1,1,PBLD010019402010,district and sessions court,0 male,0 male,0,0,644,509.0,22,2010-08-07,2013-11-25,2011-02-25,2013-11-20,2013-11-25
3613258,22-01-01-200100346712013,2010,22,1,1,PBLD010016392010,district and sessions court,1 female,0 male,0,0,644,509.0,24,2010-08-11,2011-06-07,2011-06-07,2011-06-07,2011-06-07
3613259,22-01-01-200100346842013,2010,22,1,1,PBLD010003902010,district and sessions court,0 male,1 female,-9999,-9999,644,509.0,5,2010-11-11,2014-11-25,2011-07-21,2014-11-14,2014-11-25
3613260,22-01-01-200100346852013,2010,22,1,1,PBLD010003912010,district and sessions court,1 female,1 female,-9999,-9999,644,509.0,22,2010-11-11,2014-11-25,2011-07-21,2014-11-14,2014-11-25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3718672,22-26-07-205507000812010,2010,22,26,7,PBFZC20003702010,criminal cases,0 male,0 male,0,0,3557,1963.0,4,2010-05-24,2013-07-12,2012-05-23,2013-06-07,2013-07-12
3718673,22-26-07-205507000862010,2010,22,26,7,PBFZC20003692010,criminal cases,0 male,0 male,-9999,1,3557,328.0,4,2010-05-22,2013-03-12,2012-05-09,2013-03-12,2013-03-12
3718674,22-26-07-205507001272010,2010,22,26,7,PBFZC20003712010,criminal cases,0 male,0 male,-9999,0,3557,328.0,32,2010-05-13,2013-06-14,2012-06-09,2013-05-22,2013-06-14
3718675,22-26-07-205507002482010,2010,22,26,7,PBFZC20003682010,criminal cases,0 male,0 male,-9999,0,3557,1963.0,4,2010-11-29,2013-09-02,2012-07-04,2013-08-01,2013-09-02
3718676,22-26-07-205507002832010,2010,22,26,7,PBFZC20003672010,criminal cases,0 male,0 male,-9999,0,3557,44.0,4,2010-06-12,2013-04-03,2012-05-21,2013-04-03,2013-04-03

# total cases from punjab = 5,73,146

In [9]:
len(df_2010[df_2010['state_code'] == 22]) 
+ len(df_2011[df_2011['state_code'] == 22]) 
+ len(df_2012[df_2012['state_code'] == 22]) 
+ len(df_2013[df_2013['state_code'] == 22]) 
+ len(df_2014[df_2014['state_code'] == 22]) 
+ len(df_2015[df_2015['state_code'] == 22]) 
+ len(df_2016[df_2016['state_code'] == 22]) 
+ len(df_2017[df_2017['state_code'] == 22]) 
+ len(df_2018[df_2018['state_code'] == 22])

573146